### ISSUE TITLE
Error when pip insall aisdb

### ISSUE THREAD

**Issue by Jinnkunn** [AISViz/AISdb#82]
OS: macOS 14.5

pip install aisdb
Collecting aisdb
  Using cached aisdb-1.7.2.tar.gz (313 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [160 lines of output]
      Collecting maturin>=1.0
        Using cached maturin-1.6.0-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl.metadata (18 kB)
      Collecting numpy
        Using cached numpy-1.26.4-cp39-cp39-macosx_11_0_arm64.whl.metadata (61 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting patchelf
        Using cached patchelf-0.17.2.1.tar.gz (167 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting tomli>=1.1.0 (from maturin>=1.0)
        Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
      Using cached maturin-1.6.0-py3-none-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl (15.8 MB)
      Using cached numpy-1.26.4-cp39-cp39-macosx_11_0_arm64.whl (14.0 MB)
      Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
      Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Building wheels for collected packages: patchelf
        Building wheel for patchelf (pyproject.toml): started
        Building wheel for patchelf (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for patchelf (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [126 lines of output]
      
      
            --------------------------------------------------------------------------------
            -- Trying 'Ninja' generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
              Compatibility with CMake < 3.5 will be removed from a future version of
              CMake.
      
              Update the VERSION argument <min> value or use a ...<max> suffix to tell
              CMake that the project does not need compatibility with older versions.
      
            Not searching for unused variables given on the command line.
      
            CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
            -- Configuring incomplete, errors occurred!
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying 'Ninja' generator - failure
            --------------------------------------------------------------------------------
      
      
      
            --------------------------------------------------------------------------------
            -- Trying 'Unix Makefiles' generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
              Compatibility with CMake < 3.5 will be removed from a future version of
              CMake.
      
              Update the VERSION argument <min> value or use a ...<max> suffix to tell
              CMake that the project does not need compatibility with older versions.
      
            Not searching for unused variables given on the command line.
      
            -- The C compiler identification is AppleClang 15.0.0.15000309
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - done
            -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
            -- Detecting C compile features
            -- Detecting C compile features - done
            -- The CXX compiler identification is AppleClang 15.0.0.15000309
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- Configuring done (0.3s)
            -- Generating done (0.0s)
            -- Build files have been written to: /private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-install-88ufb1qj/patchelf_426e789d7c4e4a67b6ce440c91e7d5a7/_cmake_test_compile/build
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying 'Unix Makefiles' generator - success
            --------------------------------------------------------------------------------
      
            Configuring Project
              Working directory:
                /private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-install-88ufb1qj/patchelf_426e789d7c4e4a67b6ce440c91e7d5a7/_skbuild/macosx-14.0-arm64-3.9/cmake-build
              Command:
                /opt/homebrew/bin/cmake /private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-install-88ufb1qj/patchelf_426e789d7c4e4a67b6ce440c91e7d5a7 -G 'Unix Makefiles' --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-install-88ufb1qj/patchelf_426e789d7c4e4a67b6ce440c91e7d5a7/_skbuild/macosx-14.0-arm64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.6 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-build-env-e51ae7bo/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/Users/myname/Desktop/aisdb_demo/venv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -DPYTHON_LIBRARY:PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/libpython3.9.dylib -DPython_EXECUTABLE:PATH=/Users/myname/Desktop/aisdb_demo/venv/bin/python -DPython_ROOT_DIR:PATH=/Users/myname/Desktop/aisdb_demo/venv -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -DPython3_EXECUTABLE:PATH=/Users/myname/Desktop/aisdb_demo/venv/bin/python -DPython3_ROOT_DIR:PATH=/Users/myname/Desktop/aisdb_demo/venv -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=14.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64 -DCMAKE_BUILD_TYPE:STRING=Release
      
            Not searching for unused variables given on the command line.
            -- The C compiler identification is AppleClang 15.0.0.15000309
            -- The CXX compiler identification is AppleClang 15.0.0.15000309
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - done
            -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
            -- Detecting C compile features
            -- Detecting C compile features - done
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- Configuring done (0.3s)
            -- Generating done (0.0s)
            -- Build files have been written to: /private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-install-88ufb1qj/patchelf_426e789d7c4e4a67b6ce440c91e7d5a7/_skbuild/macosx-14.0-arm64-3.9/cmake-build
            [ 11%] Creating directories for 'build_patchelf'
            [ 22%] No download step for 'build_patchelf'
            [ 33%] No update step for 'build_patchelf'
            [ 44%] Performing patch step for 'build_patchelf'
            ./bootstrap.sh: line 2: autoreconf: command not found
            make[2]: *** [build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch] Error 127
            make[1]: *** [CMakeFiles/build_patchelf.dir/all] Error 2
            make: *** [all] Error 2
            Traceback (most recent call last):
              File "/private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-build-env-e51ae7bo/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-build-env-e51ae7bo/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 697, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-build-env-e51ae7bo/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 742, in make_impl
                raise SKBuildError(msg)
      
            An error occurred while building with CMake.
              Command:
                /opt/homebrew/bin/cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-install-88ufb1qj/patchelf_426e789d7c4e4a67b6ce440c91e7d5a7
              Working directory:
                /private/var/folders/zh/thckt_q533l3r5vvgrrcfbv80000gn/T/pip-install-88ufb1qj/patchelf_426e789d7c4e4a67b6ce440c91e7d5a7/_skbuild/macosx-14.0-arm64-3.9/cmake-build
            Please check the install target is valid and see CMake's output for more information.
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build patchelf
      ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by gabrielspadon** [comment]
@Jinnkunn is this venv or docker? Can you share the Python version?

**Comment by gabrielspadon** [comment]
@Jinnkunn, I believe this is a problem with your current system and not with the package. I tested the installation on a MacBook Air M3 - macOS 14.5 on a Python 3.12.4 with a virtual env dedicated to the AISdb (version from PyPi 1.7.2).

![Screenshot 2024-07-15 at 8 32 41 AM](https://github.com/user-attachments/assets/12a2373a-5712-49b6-aa7d-43b37ac72523)
