### ISSUE TITLE
Map not showing when BigData-1 is offline

### ISSUE THREAD

**Issue by gabrielspadon** [AISViz/AISdb#86]
@Jinnkunn, when using the visualization function from AISdb, @tsuzzy noticed that the background map that shows in the visualization is not showing locally. @tsuzzy mentioned that could be due to a WebSocket communication with BigData-1 that is not happening due to it being offline. I wonder why we need to communicate with BD1 if we are running locally. For instance, PlotLy can show map visualizations without realying in external sources. Can't we pack the map shapefile into what we are doing?

**Comment by Jinnkunn** [comment]
The new version of the frontend code is currently in development and will address this issue.
