### ISSUE TITLE
Error processing .nm4 and .nmea files

### ISSUE THREAD

**Issue by tsuzzy** [AISViz/AISdb#93]
When using the function `aisdb.database.decode_msgs()` to decode and process .nm4 and .nmea files, the following message is prompted:
```
error processing path/to/filename.nm4, skipping checksum...
```
This results in an empty table being created in the SQLite database.

The issue can be reproduced with the following code,:
```
import aisdb

filepath = ['./sample_data.nm4']

with aisdb.DBConn(dbpath = 'sample.db') as dbconn:
    aisdb.decode_msgs(filepaths=filepath, dbconn=dbconn, source='TESTING')
```
Content in `sample_data.nm4` is:
```
\s:41925,c:1635731906,t:1635731966*63\!AIVDM,1,1,,,11mg=5@000<Oe=Cbv:E@08L`00Ra,0*41
\s:41925,c:1635731906,t:1635731966*63\!AIVDM,1,1,,,15Utl40P0:<2TeiUEfmbk?vd08=T,0*78
```
Expected the file should be processed and data should be populated in the database.

Actual output:
```
generating file checksums...
checking file dates...
creating tables and dropping table indexes...
Memory: 21.92GB remaining.  CPUs: 12.  Average file size: 0.00MB  Spawning 4 workers
processing ./sample_data.nm4
saving checksums...
error processing ./sample_data.nm4, skipping checksum...
cleaning temporary data...
```
As observed, the message indicates a failure in processing the file, leading to the checksum being skipped and an empty table in the database.
Running the test script `test_002_decode.py` produces a similar output. However, the test passes because this failure does not raise any errors.

Environment:
 - OS: Ubuntu 22.04.4 LTS
 - Python version: 3.10.12
 - AISdb version: 1.7.3

**Comment by gabrielspadon** [comment]
Related to #78 , please address this issue as well.

**Comment by gabrielspadon** [comment]
Also related to #85 , please address this issue as well.
